### ISSUE TITLE
Do stránky s výběrem preferencí přidat čísla pořadí pro lepší orientaci

### ISSUE THREAD

**Issue by podlomar** [podlomar/meetyourmentor#24]

**Comment by FilipJirsak** [comment]
Napadlo mne včera to samé. Přidal bych doleva před řádek s týmem (obdélník) pořadové číslo v kolečku, kolečko by zůstávalo na místě a drag&dropoval by se jen ten obdélník s týmem.
Po vyhodnocení bych pak zobrazil týmy stejným způsobem – tj. kolečko s pořadím a vedle něj obdélník s názvem týmu a členy. Tím, že to bude vizuálně stejné, jako na stránce s výběrem preferencí, bude snad jasnější, k čemu se to pořadí vztahuje.

**Comment by FilipJirsak** [comment]
Takhle nějak by to mohlo vypadat (berte to jako wire frame, ne jako finální vzhled):
![image](https://github.com/podlomar/meetyourmentor/assets/2570553/6bd17acf-9221-42de-8de4-3c322ece881d)

Jsou tam použité takovéto styly:
Kontejner obalující celý řádek:
```css
display: flex;
align-items: center;
```

Pořadové číslo:
```css
background-color: #43454d;
border-radius: 50%;
width: 40px;
height: 40px;
margin-right: 20px;
display: flex;
justify-content: center;
align-items: center;
```

Obdélníku s názvem týmu jsem přidal:
```css
flex: 1;
```

Rozhodně to není finální řešení, jenom ať kdyžtak není potřeba vymýšlet vše od nuly. Třeba to pořadové číslo je v CSS vycentrované, ale na mne vizuálně působí, že je posunuté dolů, takže tam asi bude nějaký problém.

**Comment by podlomar** [comment]
Bohužel se to hrozně těžko implementuje tak, aby se dalo hýbat jen těmi obdélníčky a ne těmi čísly. Čísla a položky by musely být v oddělených divech, protože SortableJS potřebuje, ale položky pro přesouvání byly přímé děti kontejneru. Potom je ale těžké zarovnat pomocí CSS čísla a položky, pokud bude nějaká položka moc dlouhá. 

Jde to potenciálně vyřešit pomocí `subgrid` property, ale tu Chrome podporuje teprve od září 2023, což je moc novinka na to, abych si to troufl použít. Takže je to teď takový trochu kompromis, že se přesouvají i ta čísla.

Kdyby měl někdo @FilipJirsak, @EvaMach nápad, jak to obejít, sem s ním.

**Comment by EvaMach** [comment]
Už jsem tomu taky hodinu věnovala a došla ke stejnému závěru. Buď subgrid a nebo dat fixní výšku i těm boxíkům a prostě to absolutně zarovnat.

**Comment by podlomar** [comment]
Ok, tak to zatím nechme tak, jak je to v tom pull requestu
