### ISSUE TITLE
Na stránce s výsledky zobrazit týmy pod sebou, ne vedle sebe

### ISSUE THREAD

**Issue by FilipJirsak** [podlomar/meetyourmentor#29]
Na stránce s výsledky párování všech týmů zobrazit dvojice mentors:mentees pod sebou, ne vedle sebe. Názvy týmů jsou poměrně dlouhé a když je to vedle sebe, ošklivě se to zalamuje.
Když budou týmy pod sebou, zobrazil bych je stejně, jako na stránce s výběrem preferencí – kolečko s pořadovým číslem (viz  #24, jaké měl u protějšího týmu), a vedle obdélník s názvem týmu. Tím, že to bude vizuálně stejné, jako na stránce s výběrem preferencí, bude snad jasnější, k čemu to pořadí patří. (Když je teď zobrazeno *Mentoři A 1:2 Tým 1*, není z toho jasné, zda Mentoři A měli na prvním místě Tým 1, nebo zda Tým 1 měl na prvním místě Mentory A.)

**Comment by FilipJirsak** [comment]
Ta stránka s výsledky by mohla vypadat takhle nějak (zase to berte jako wire frame):
![image](https://github.com/podlomar/meetyourmentor/assets/2570553/55a5d13b-035e-47f2-af6d-4f1de27035fd)

**Comment by EvaMach** [comment]
Mně přijde asi intuitivnější to aktuální pořadí. Když si pak rozkliknu "open preferences", tak tam vidím vlastně stejné číslo - tedy, že tým A má zvýrazněný projekt 2. v pořadí. Takže skóre týmu A je 2. Když by tam bylo něco jiného, tak bych nad tím asi musela přemýšlet víc. Nevím, jak to má @podlomar? Pro letos bych to asi ještě nechala, jak bylo původně, ale dám je pod sebe, aby se to ošklivě nezalamovala, jak říkáš.
