### ISSUE TITLE
Undefined v url

### ISSUE THREAD

**Issue by EvaMach** [podlomar/meetyourmentor#9]

**Comment by podlomar** [comment]
To undefined tam bylo kvůli chybějící environment variable na serveru, už jsem to opravil, jen ta adresa teď hodně leze z těch boxů

![image](https://github.com/podlomar/meetyourmentor/assets/4608335/67ff3f5b-41e1-4e03-82a2-359ca3ff392a)

Tak by to asi chtělo to UI udělat nějak takhle:

![image](https://github.com/podlomar/meetyourmentor/assets/4608335/3a2f2d25-d564-4410-8b5d-ea86968965cc)
